name: CI + Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  pages: write
  id-token: write

jobs:
  # -----------------------------
  # Build / Test job (run on PR, main push, or manual)
  # -----------------------------
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x

      - name: Update submodules
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: git submodule update --init --recursive

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build Docs
        run: docfx doc/docfx.json

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc/_site'

  # -----------------------------
  # Deploy job (only run on push to main)
  # -----------------------------
  deploy-pages:
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4